### ISSUE TITLE
Why mount a local lib into the container?

### ISSUE THREAD

**Issue by Izhaki** [SmartInfrastructures/rancher-setup-notes#1]
The `docker-compose.yml` in the README file has the following:

```
  rancher:
    container_name: rancher-server
    image: rancher/server:${RANCHER_VERSION}
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=${RANCHER_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${RANCHER_HOSTNAME}
      - LETSENCRYPT_EMAIL=${RENEWAL_EMAIL}
      - LETSENCTYPT_TEST=true
    volumes:
      # TODO: something seems wrong here, why mount a local lib into
      # the container?
      - /var/lib/mysql:/var/lib/mysql:rw
```

Just dropping a line to say that this is done so rancher's sql database is stored on the host and not within the docker image.
